apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: otonomo
spec:
  selector:
      matchLabels:
        app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: naimcivalue/devops_challenge:1.1
#          imagePullSecrets:
#            - name: docker-registry
